'use client'

import "./globals.css";
import { Manrope } from "next/font/google";
import Navbar from "./components/Navbar";
import { usePathname } from "next/navigation";
import Cart from "./components/Cart";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Audiophile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const pathname = usePathname()

  return (
    <html lang="en">
      <body className={`${manrope.className}`}>
        <div className={`${pathname === "/" ? "absolute top-0 left-0 right-0 z-20" : ""}`}>
          <Navbar />
        </div>
        {children}
        <Cart />
      </body>
    </html>
  );
}
